package M1_4_ScenarioPlanning.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptBusinessDriver = createDescriptorForBusinessDriver();
  /*package*/ final ConceptDescriptor myConceptCasual = createDescriptorForCasual();
  /*package*/ final ConceptDescriptor myConceptCheckPoint = createDescriptorForCheckPoint();
  /*package*/ final ConceptDescriptor myConceptDynamicsSimulation = createDescriptorForDynamicsSimulation();
  /*package*/ final ConceptDescriptor myConceptInfluence = createDescriptorForInfluence();
  /*package*/ final ConceptDescriptor myConceptKPI = createDescriptorForKPI();
  /*package*/ final ConceptDescriptor myConceptKpiModel = createDescriptorForKpiModel();
  /*package*/ final ConceptDescriptor myConceptLinkEditor = createDescriptorForLinkEditor();
  /*package*/ final ConceptDescriptor myConceptProduct = createDescriptorForProduct();
  /*package*/ final ConceptDescriptor myConceptRoadmapEditor = createDescriptorForRoadmapEditor();
  /*package*/ final ConceptDescriptor myConceptScenarioShift = createDescriptorForScenarioShift();
  /*package*/ final ConceptDescriptor myConceptService = createDescriptorForService();
  /*package*/ final ConceptDescriptor myConceptSimulationEditor = createDescriptorForSimulationEditor();
  /*package*/ final ConceptDescriptor myConceptTechnology = createDescriptorForTechnology();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0x4b68402a1c7b472dL, 0x8c517b3c81719d43L, "M2_AbstractLanguage");
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
    deps.aggregatedLanguage(0x4b68402a1c7b472dL, 0x8c517b3c81719d43L, "M2_AbstractLanguage");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptBusinessDriver, myConceptCasual, myConceptCheckPoint, myConceptDynamicsSimulation, myConceptInfluence, myConceptKPI, myConceptKpiModel, myConceptLinkEditor, myConceptProduct, myConceptRoadmapEditor, myConceptScenarioShift, myConceptService, myConceptSimulationEditor, myConceptTechnology);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.BusinessDriver:
        return myConceptBusinessDriver;
      case LanguageConceptSwitch.Casual:
        return myConceptCasual;
      case LanguageConceptSwitch.CheckPoint:
        return myConceptCheckPoint;
      case LanguageConceptSwitch.DynamicsSimulation:
        return myConceptDynamicsSimulation;
      case LanguageConceptSwitch.Influence:
        return myConceptInfluence;
      case LanguageConceptSwitch.KPI:
        return myConceptKPI;
      case LanguageConceptSwitch.KpiModel:
        return myConceptKpiModel;
      case LanguageConceptSwitch.LinkEditor:
        return myConceptLinkEditor;
      case LanguageConceptSwitch.Product:
        return myConceptProduct;
      case LanguageConceptSwitch.RoadmapEditor:
        return myConceptRoadmapEditor;
      case LanguageConceptSwitch.ScenarioShift:
        return myConceptScenarioShift;
      case LanguageConceptSwitch.Service:
        return myConceptService;
      case LanguageConceptSwitch.SimulationEditor:
        return myConceptSimulationEditor;
      case LanguageConceptSwitch.Technology:
        return myConceptTechnology;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForBusinessDriver() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("M1_4_ScenarioPlanning", "BusinessDriver", 0xaee53256d5314aefL, 0xa69aa7f9142b644dL, 0x5ff61aa790335c9dL);
    b.class_(false, false, false);
    b.super_("M2_AbstractLanguage.structure.Element", 0x4b68402a1c7b472dL, 0x8c517b3c81719d43L, 0x7157f84cd39fdab8L);
    b.origin("r:a9358a5b-1124-43ad-ac2f-dca0ab376f36(M1_4_ScenarioPlanning.structure)/6914743584855121053");
    b.version(2);
    b.alias("Business Driver");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCasual() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("M1_4_ScenarioPlanning", "Casual", 0xaee53256d5314aefL, 0xa69aa7f9142b644dL, 0x12ac17505577641L);
    b.class_(false, false, false);
    b.super_("M2_AbstractLanguage.structure.Link", 0x4b68402a1c7b472dL, 0x8c517b3c81719d43L, 0x7157f84cd376c8cfL);
    b.origin("r:a9358a5b-1124-43ad-ac2f-dca0ab376f36(M1_4_ScenarioPlanning.structure)/84092251404727873");
    b.version(2);
    b.alias("causes");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCheckPoint() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("M1_4_ScenarioPlanning", "CheckPoint", 0xaee53256d5314aefL, 0xa69aa7f9142b644dL, 0x5ff61aa790335ca3L);
    b.class_(false, false, false);
    b.super_("M2_AbstractLanguage.structure.Element", 0x4b68402a1c7b472dL, 0x8c517b3c81719d43L, 0x7157f84cd39fdab8L);
    b.origin("r:a9358a5b-1124-43ad-ac2f-dca0ab376f36(M1_4_ScenarioPlanning.structure)/6914743584855121059");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDynamicsSimulation() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("M1_4_ScenarioPlanning", "DynamicsSimulation", 0xaee53256d5314aefL, 0xa69aa7f9142b644dL, 0x5fd117c68b996244L);
    b.class_(false, false, false);
    b.parent(0x4b68402a1c7b472dL, 0x8c517b3c81719d43L, 0x5fd117c68b9e1eaeL);
    b.origin("r:a9358a5b-1124-43ad-ac2f-dca0ab376f36(M1_4_ScenarioPlanning.structure)/6904325845248729668");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForInfluence() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("M1_4_ScenarioPlanning", "Influence", 0xaee53256d5314aefL, 0xa69aa7f9142b644dL, 0x5ff61aa790335ca5L);
    b.class_(false, false, false);
    b.super_("M2_AbstractLanguage.structure.Link", 0x4b68402a1c7b472dL, 0x8c517b3c81719d43L, 0x7157f84cd376c8cfL);
    b.origin("r:a9358a5b-1124-43ad-ac2f-dca0ab376f36(M1_4_ScenarioPlanning.structure)/6914743584855121061");
    b.version(2);
    b.alias("influence");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForKPI() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("M1_4_ScenarioPlanning", "KPI", 0xaee53256d5314aefL, 0xa69aa7f9142b644dL, 0x12ac17505633a26L);
    b.class_(false, false, false);
    b.super_("M2_AbstractLanguage.structure.Element", 0x4b68402a1c7b472dL, 0x8c517b3c81719d43L, 0x7157f84cd39fdab8L);
    b.origin("r:a9358a5b-1124-43ad-ac2f-dca0ab376f36(M1_4_ScenarioPlanning.structure)/84092251405498918");
    b.version(2);
    b.aggregate("kpiModel", 0x12ac175058598c9L).target(0xaee53256d5314aefL, 0xa69aa7f9142b644dL, 0x12ac17505635673L).optional(true).ordered(true).multiple(false).origin("84092251407751369").done();
    b.alias("Key Performance Indicator");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForKpiModel() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("M1_4_ScenarioPlanning", "KpiModel", 0xaee53256d5314aefL, 0xa69aa7f9142b644dL, 0x12ac17505635673L);
    b.class_(false, false, false);
    b.super_("M2_AbstractLanguage.structure.ModelConfiguration", 0x4b68402a1c7b472dL, 0x8c517b3c81719d43L, 0x7157f84cd3adb99cL);
    b.origin("r:a9358a5b-1124-43ad-ac2f-dca0ab376f36(M1_4_ScenarioPlanning.structure)/84092251405506163");
    b.version(2);
    b.property("model", 0x12ac17505859920L).type(PrimitiveTypeId.STRING).origin("84092251407751456").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLinkEditor() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("M1_4_ScenarioPlanning", "LinkEditor", 0xaee53256d5314aefL, 0xa69aa7f9142b644dL, 0x12ac1750551e8a1L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:a9358a5b-1124-43ad-ac2f-dca0ab376f36(M1_4_ScenarioPlanning.structure)/84092251404363937");
    b.version(2);
    b.aggregate("links", 0x12ac1750551e8a3L).target(0x4b68402a1c7b472dL, 0x8c517b3c81719d43L, 0x7157f84cd376c8cfL).optional(true).ordered(true).multiple(true).origin("84092251404363939").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForProduct() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("M1_4_ScenarioPlanning", "Product", 0xaee53256d5314aefL, 0xa69aa7f9142b644dL, 0x5ff61aa790335c9fL);
    b.class_(false, false, false);
    b.super_("M2_AbstractLanguage.structure.Element", 0x4b68402a1c7b472dL, 0x8c517b3c81719d43L, 0x7157f84cd39fdab8L);
    b.origin("r:a9358a5b-1124-43ad-ac2f-dca0ab376f36(M1_4_ScenarioPlanning.structure)/6914743584855121055");
    b.version(2);
    b.alias("Product");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRoadmapEditor() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("M1_4_ScenarioPlanning", "RoadmapEditor", 0xaee53256d5314aefL, 0xa69aa7f9142b644dL, 0x5fd117c68b5e1854L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:a9358a5b-1124-43ad-ac2f-dca0ab376f36(M1_4_ScenarioPlanning.structure)/6904325845244844116");
    b.version(2);
    b.aggregate("elements", 0x5fd117c68b5ed1b0L).target(0x4b68402a1c7b472dL, 0x8c517b3c81719d43L, 0x7157f84cd39fdab8L).optional(true).ordered(true).multiple(true).origin("6904325845244891568").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForScenarioShift() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("M1_4_ScenarioPlanning", "ScenarioShift", 0xaee53256d5314aefL, 0xa69aa7f9142b644dL, 0x5ff61aa790335ca4L);
    b.class_(false, false, false);
    b.super_("M2_AbstractLanguage.structure.Link", 0x4b68402a1c7b472dL, 0x8c517b3c81719d43L, 0x7157f84cd376c8cfL);
    b.origin("r:a9358a5b-1124-43ad-ac2f-dca0ab376f36(M1_4_ScenarioPlanning.structure)/6914743584855121060");
    b.version(2);
    b.alias("causes");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForService() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("M1_4_ScenarioPlanning", "Service", 0xaee53256d5314aefL, 0xa69aa7f9142b644dL, 0x5ff61aa790335ca2L);
    b.class_(false, false, false);
    b.super_("M2_AbstractLanguage.structure.Element", 0x4b68402a1c7b472dL, 0x8c517b3c81719d43L, 0x7157f84cd39fdab8L);
    b.origin("r:a9358a5b-1124-43ad-ac2f-dca0ab376f36(M1_4_ScenarioPlanning.structure)/6914743584855121058");
    b.version(2);
    b.alias("Service");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSimulationEditor() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("M1_4_ScenarioPlanning", "SimulationEditor", 0xaee53256d5314aefL, 0xa69aa7f9142b644dL, 0x12ac1750585993bL);
    b.class_(false, false, true);
    b.origin("r:a9358a5b-1124-43ad-ac2f-dca0ab376f36(M1_4_ScenarioPlanning.structure)/84092251407751483");
    b.version(2);
    b.aggregate("influence", 0x12ac1750585993cL).target(0xaee53256d5314aefL, 0xa69aa7f9142b644dL, 0x5ff61aa790335ca5L).optional(true).ordered(true).multiple(true).origin("84092251407751484").done();
    b.aggregate("kpi", 0x12ac1750585993eL).target(0xaee53256d5314aefL, 0xa69aa7f9142b644dL, 0x12ac17505633a26L).optional(true).ordered(true).multiple(true).origin("84092251407751486").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTechnology() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("M1_4_ScenarioPlanning", "Technology", 0xaee53256d5314aefL, 0xa69aa7f9142b644dL, 0x5ff61aa790335c9eL);
    b.class_(false, false, false);
    b.super_("M2_AbstractLanguage.structure.Element", 0x4b68402a1c7b472dL, 0x8c517b3c81719d43L, 0x7157f84cd39fdab8L);
    b.origin("r:a9358a5b-1124-43ad-ac2f-dca0ab376f36(M1_4_ScenarioPlanning.structure)/6914743584855121054");
    b.version(2);
    b.alias("Technology");
    return b.create();
  }
}
