package M1_1_ToyDomainLanguage.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new ElementClassList_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new ElementList_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new ElementTrm_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new Evolve_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new ProductClass_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }



  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xb41c0bb62cc44e40L, 0xb4f3a42ad3dd9098L, 0x7157f84cd39eeedcL), MetaIdFactory.conceptId(0xb41c0bb62cc44e40L, 0xb4f3a42ad3dd9098L, 0x7157f84cd3a3d1afL), MetaIdFactory.conceptId(0xb41c0bb62cc44e40L, 0xb4f3a42ad3dd9098L, 0x4742492ef6cbb067L), MetaIdFactory.conceptId(0xb41c0bb62cc44e40L, 0xb4f3a42ad3dd9098L, 0x7157f84cd3a18171L), MetaIdFactory.conceptId(0xb41c0bb62cc44e40L, 0xb4f3a42ad3dd9098L, 0x7157f84cd3992262L)).seal();
}
