package M1_4_ScenarioPlanning.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.core.aspects.behaviour.api.SMethod;
import jetbrains.mps.core.aspects.behaviour.SMethodBuilder;
import jetbrains.mps.core.aspects.behaviour.SJavaCompoundTypeImpl;
import jetbrains.mps.core.aspects.behaviour.SModifiersImpl;
import jetbrains.mps.core.aspects.behaviour.AccessPrivileges;
import java.util.List;
import java.util.Arrays;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.core.aspects.behaviour.api.SConstructor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.core.aspects.behaviour.api.BHMethodNotFoundException;

public final class DynamicsSimulation__BehaviorDescriptor extends BaseBHDescriptor {
  private static final SAbstractConcept CONCEPT = MetaAdapterFactory.getConcept(0xaee53256d5314aefL, 0xa69aa7f9142b644dL, 0x5fd117c68b996244L, "M1_4_ScenarioPlanning.structure.DynamicsSimulation");

  public static final SMethod<Void> traverseGraph_id5Zh5Wqb_Tnq = new SMethodBuilder<Void>(new SJavaCompoundTypeImpl(Void.class)).name("traverseGraph").modifiers(SModifiersImpl.create(8, AccessPrivileges.PUBLIC)).concept(CONCEPT).id("5Zh5Wqb_Tnq").build();
  public static final SMethod<Void> calculate_id5Zh5Wqb_TrJ = new SMethodBuilder<Void>(new SJavaCompoundTypeImpl(Void.class)).name("calculate").modifiers(SModifiersImpl.create(8, AccessPrivileges.PUBLIC)).concept(CONCEPT).id("5Zh5Wqb_TrJ").build();
  public static final SMethod<Void> run_id5Zh5Wqb_T$R = new SMethodBuilder<Void>(new SJavaCompoundTypeImpl(Void.class)).name("run").modifiers(SModifiersImpl.create(8, AccessPrivileges.PUBLIC)).concept(CONCEPT).id("5Zh5Wqb_T$R").build();

  private static final List<SMethod<?>> BH_METHODS = Arrays.<SMethod<?>>asList(traverseGraph_id5Zh5Wqb_Tnq, calculate_id5Zh5Wqb_TrJ, run_id5Zh5Wqb_T$R);

  private static void ___init___(@NotNull SNode __thisNode__) {
  }

  /*package*/ static void traverseGraph_id5Zh5Wqb_Tnq(@NotNull SNode __thisNode__) {
  }
  /*package*/ static void calculate_id5Zh5Wqb_TrJ(@NotNull SNode __thisNode__) {
  }
  /*package*/ static void run_id5Zh5Wqb_T$R(@NotNull SNode __thisNode__) {
  }

  /*package*/ DynamicsSimulation__BehaviorDescriptor() {
  }

  @Override
  protected void initNode(@NotNull SNode node, @NotNull SConstructor constructor, @Nullable Object[] parameters) {
    ___init___(node);
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SNode node, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      case 0:
        traverseGraph_id5Zh5Wqb_Tnq(node);
        return null;
      case 1:
        calculate_id5Zh5Wqb_TrJ(node);
        return null;
      case 2:
        run_id5Zh5Wqb_T$R(node);
        return null;
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SAbstractConcept concept, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @NotNull
  @Override
  public List<SMethod<?>> getDeclaredMethods() {
    return BH_METHODS;
  }

  @NotNull
  @Override
  public SAbstractConcept getConcept() {
    return CONCEPT;
  }
}
