package M1_2_DesignRoadmapping.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int AudFeedback = 0;
  public static final int CoreExperience = 1;
  public static final int ElementList = 2;
  public static final int Evolve = 3;
  public static final int FormFactor = 4;
  public static final int KeyFeature = 5;
  public static final int Microcontroller = 6;
  public static final int Outcome = 7;
  public static final int Power = 8;
  public static final int PrimaryUserNeed = 9;
  public static final int Requires = 10;
  public static final int Satisfies = 11;
  public static final int ScreenInterface = 12;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xa3ca47195a3a4b22L, 0x9db2d6b600fc0223L);
    builder.put(0x4742492ef6d05c17L, AudFeedback);
    builder.put(0x4742492ef6d0566aL, CoreExperience);
    builder.put(0x4742492ef6d05c97L, ElementList);
    builder.put(0x7157f84cd3a18171L, Evolve);
    builder.put(0x4742492ef6d05c51L, FormFactor);
    builder.put(0x4742492ef6d0568bL, KeyFeature);
    builder.put(0x4742492ef6d05692L, Microcontroller);
    builder.put(0x4742492ef6d0566fL, Outcome);
    builder.put(0x4742492ef6d05c4eL, Power);
    builder.put(0x4742492ef6d0566dL, PrimaryUserNeed);
    builder.put(0x4742492ef6df268cL, Requires);
    builder.put(0x4742492ef6dc6ff1L, Satisfies);
    builder.put(0x4742492ef6d05695L, ScreenInterface);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
