package M1_2_DesignRoadmapping.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAudFeedback = createDescriptorForAudFeedback();
  /*package*/ final ConceptDescriptor myConceptCoreExperience = createDescriptorForCoreExperience();
  /*package*/ final ConceptDescriptor myConceptElementList = createDescriptorForElementList();
  /*package*/ final ConceptDescriptor myConceptEvolve = createDescriptorForEvolve();
  /*package*/ final ConceptDescriptor myConceptFormFactor = createDescriptorForFormFactor();
  /*package*/ final ConceptDescriptor myConceptKeyFeature = createDescriptorForKeyFeature();
  /*package*/ final ConceptDescriptor myConceptMicrocontroller = createDescriptorForMicrocontroller();
  /*package*/ final ConceptDescriptor myConceptOutcome = createDescriptorForOutcome();
  /*package*/ final ConceptDescriptor myConceptPower = createDescriptorForPower();
  /*package*/ final ConceptDescriptor myConceptPrimaryUserNeed = createDescriptorForPrimaryUserNeed();
  /*package*/ final ConceptDescriptor myConceptRequires = createDescriptorForRequires();
  /*package*/ final ConceptDescriptor myConceptSatisfies = createDescriptorForSatisfies();
  /*package*/ final ConceptDescriptor myConceptScreenInterface = createDescriptorForScreenInterface();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0x4b68402a1c7b472dL, 0x8c517b3c81719d43L, "M2_AbstractLanguage");
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
    deps.aggregatedLanguage(0x4b68402a1c7b472dL, 0x8c517b3c81719d43L, "M2_AbstractLanguage");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAudFeedback, myConceptCoreExperience, myConceptElementList, myConceptEvolve, myConceptFormFactor, myConceptKeyFeature, myConceptMicrocontroller, myConceptOutcome, myConceptPower, myConceptPrimaryUserNeed, myConceptRequires, myConceptSatisfies, myConceptScreenInterface);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.AudFeedback:
        return myConceptAudFeedback;
      case LanguageConceptSwitch.CoreExperience:
        return myConceptCoreExperience;
      case LanguageConceptSwitch.ElementList:
        return myConceptElementList;
      case LanguageConceptSwitch.Evolve:
        return myConceptEvolve;
      case LanguageConceptSwitch.FormFactor:
        return myConceptFormFactor;
      case LanguageConceptSwitch.KeyFeature:
        return myConceptKeyFeature;
      case LanguageConceptSwitch.Microcontroller:
        return myConceptMicrocontroller;
      case LanguageConceptSwitch.Outcome:
        return myConceptOutcome;
      case LanguageConceptSwitch.Power:
        return myConceptPower;
      case LanguageConceptSwitch.PrimaryUserNeed:
        return myConceptPrimaryUserNeed;
      case LanguageConceptSwitch.Requires:
        return myConceptRequires;
      case LanguageConceptSwitch.Satisfies:
        return myConceptSatisfies;
      case LanguageConceptSwitch.ScreenInterface:
        return myConceptScreenInterface;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAudFeedback() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("M1_2_DesignRoadmapping", "AudFeedback", 0xa3ca47195a3a4b22L, 0x9db2d6b600fc0223L, 0x4742492ef6d05c17L);
    b.class_(false, false, false);
    b.super_("M2_AbstractLanguage.structure.Element", 0x4b68402a1c7b472dL, 0x8c517b3c81719d43L, 0x7157f84cd39fdab8L);
    b.origin("r:bec4dda7-5c83-4544-bebd-5932074c8254(M1_2_DesignRoadmapping.structure)/5134746991213960215");
    b.version(2);
    b.property("description", 0x4742492ef6d05696L).type(PrimitiveTypeId.STRING).origin("5134746991213960216").done();
    b.alias("Auditory Feedback");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCoreExperience() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("M1_2_DesignRoadmapping", "CoreExperience", 0xa3ca47195a3a4b22L, 0x9db2d6b600fc0223L, 0x4742492ef6d0566aL);
    b.class_(false, false, false);
    b.super_("M2_AbstractLanguage.structure.Element", 0x4b68402a1c7b472dL, 0x8c517b3c81719d43L, 0x7157f84cd39fdab8L);
    b.origin("r:bec4dda7-5c83-4544-bebd-5932074c8254(M1_2_DesignRoadmapping.structure)/5134746991213958762");
    b.version(2);
    b.property("description", 0x4742492ef6d0566bL).type(PrimitiveTypeId.STRING).origin("5134746991213958763").done();
    b.alias("Core Experience");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForElementList() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("M1_2_DesignRoadmapping", "ElementList", 0xa3ca47195a3a4b22L, 0x9db2d6b600fc0223L, 0x4742492ef6d05c97L);
    b.class_(false, false, true);
    b.origin("r:bec4dda7-5c83-4544-bebd-5932074c8254(M1_2_DesignRoadmapping.structure)/5134746991213960343");
    b.version(2);
    b.aggregate("core_exps", 0x4742492ef6d05c9cL).target(0xa3ca47195a3a4b22L, 0x9db2d6b600fc0223L, 0x4742492ef6d0566aL).optional(true).ordered(true).multiple(true).origin("5134746991213960348").done();
    b.aggregate("user_needs", 0x4742492ef6d05c9fL).target(0xa3ca47195a3a4b22L, 0x9db2d6b600fc0223L, 0x4742492ef6d0566dL).optional(true).ordered(true).multiple(true).origin("5134746991213960351").done();
    b.aggregate("outcomes", 0x4742492ef6d05ca3L).target(0xa3ca47195a3a4b22L, 0x9db2d6b600fc0223L, 0x4742492ef6d0566fL).optional(true).ordered(true).multiple(true).origin("5134746991213960355").done();
    b.aggregate("key_features", 0x4742492ef6d05cb2L).target(0xa3ca47195a3a4b22L, 0x9db2d6b600fc0223L, 0x4742492ef6d0568bL).optional(true).ordered(true).multiple(true).origin("5134746991213960370").done();
    b.aggregate("microcontrollers", 0x4742492ef6d05cb8L).target(0xa3ca47195a3a4b22L, 0x9db2d6b600fc0223L, 0x4742492ef6d05692L).optional(true).ordered(true).multiple(true).origin("5134746991213960376").done();
    b.aggregate("screen_interface", 0x4742492ef6d05cbfL).target(0xa3ca47195a3a4b22L, 0x9db2d6b600fc0223L, 0x4742492ef6d05695L).optional(true).ordered(true).multiple(true).origin("5134746991213960383").done();
    b.aggregate("auditory", 0x4742492ef6d05c9aL).target(0xa3ca47195a3a4b22L, 0x9db2d6b600fc0223L, 0x4742492ef6d05c17L).optional(true).ordered(true).multiple(true).origin("5134746991213960346").done();
    b.aggregate("power", 0x4742492ef6d05cd7L).target(0xa3ca47195a3a4b22L, 0x9db2d6b600fc0223L, 0x4742492ef6d05c4eL).optional(true).ordered(true).multiple(true).origin("5134746991213960407").done();
    b.aggregate("form_factor", 0x4742492ef6d05ce0L).target(0xa3ca47195a3a4b22L, 0x9db2d6b600fc0223L, 0x4742492ef6d05c51L).optional(true).ordered(true).multiple(true).origin("5134746991213960416").done();
    b.aggregate("links", 0x4742492ef6dcfa70L).target(0x4b68402a1c7b472dL, 0x8c517b3c81719d43L, 0x7157f84cd376c8cfL).optional(true).ordered(true).multiple(true).origin("5134746991214787184").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForEvolve() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("M1_2_DesignRoadmapping", "Evolve", 0xa3ca47195a3a4b22L, 0x9db2d6b600fc0223L, 0x7157f84cd3a18171L);
    b.class_(false, false, false);
    b.super_("M2_AbstractLanguage.structure.Link", 0x4b68402a1c7b472dL, 0x8c517b3c81719d43L, 0x7157f84cd376c8cfL);
    b.origin("r:bec4dda7-5c83-4544-bebd-5932074c8254(M1_2_DesignRoadmapping.structure)/8167269458111463793");
    b.version(2);
    b.alias("evolves to");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForFormFactor() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("M1_2_DesignRoadmapping", "FormFactor", 0xa3ca47195a3a4b22L, 0x9db2d6b600fc0223L, 0x4742492ef6d05c51L);
    b.class_(false, false, false);
    b.super_("M2_AbstractLanguage.structure.Element", 0x4b68402a1c7b472dL, 0x8c517b3c81719d43L, 0x7157f84cd39fdab8L);
    b.origin("r:bec4dda7-5c83-4544-bebd-5932074c8254(M1_2_DesignRoadmapping.structure)/5134746991213960273");
    b.version(2);
    b.property("description", 0x4742492ef6d05c52L).type(PrimitiveTypeId.STRING).origin("5134746991213960274").done();
    b.alias("Form Factor");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForKeyFeature() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("M1_2_DesignRoadmapping", "KeyFeature", 0xa3ca47195a3a4b22L, 0x9db2d6b600fc0223L, 0x4742492ef6d0568bL);
    b.class_(false, false, false);
    b.super_("M2_AbstractLanguage.structure.Element", 0x4b68402a1c7b472dL, 0x8c517b3c81719d43L, 0x7157f84cd39fdab8L);
    b.origin("r:bec4dda7-5c83-4544-bebd-5932074c8254(M1_2_DesignRoadmapping.structure)/5134746991213958795");
    b.version(2);
    b.property("description", 0x4742492ef6d0568cL).type(PrimitiveTypeId.STRING).origin("5134746991213958796").done();
    b.alias("Key Function/Feature");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForMicrocontroller() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("M1_2_DesignRoadmapping", "Microcontroller", 0xa3ca47195a3a4b22L, 0x9db2d6b600fc0223L, 0x4742492ef6d05692L);
    b.class_(false, false, false);
    b.super_("M2_AbstractLanguage.structure.Element", 0x4b68402a1c7b472dL, 0x8c517b3c81719d43L, 0x7157f84cd39fdab8L);
    b.origin("r:bec4dda7-5c83-4544-bebd-5932074c8254(M1_2_DesignRoadmapping.structure)/5134746991213958802");
    b.version(2);
    b.property("description", 0x4742492ef6d05693L).type(PrimitiveTypeId.STRING).origin("5134746991213958803").done();
    b.alias("Micro-Controller");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForOutcome() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("M1_2_DesignRoadmapping", "Outcome", 0xa3ca47195a3a4b22L, 0x9db2d6b600fc0223L, 0x4742492ef6d0566fL);
    b.class_(false, false, false);
    b.super_("M2_AbstractLanguage.structure.Element", 0x4b68402a1c7b472dL, 0x8c517b3c81719d43L, 0x7157f84cd39fdab8L);
    b.origin("r:bec4dda7-5c83-4544-bebd-5932074c8254(M1_2_DesignRoadmapping.structure)/5134746991213958767");
    b.version(2);
    b.property("description", 0x4742492ef6d0568eL).type(PrimitiveTypeId.STRING).origin("5134746991213958798").done();
    b.alias("Outcome");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPower() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("M1_2_DesignRoadmapping", "Power", 0xa3ca47195a3a4b22L, 0x9db2d6b600fc0223L, 0x4742492ef6d05c4eL);
    b.class_(false, false, false);
    b.super_("M2_AbstractLanguage.structure.Element", 0x4b68402a1c7b472dL, 0x8c517b3c81719d43L, 0x7157f84cd39fdab8L);
    b.origin("r:bec4dda7-5c83-4544-bebd-5932074c8254(M1_2_DesignRoadmapping.structure)/5134746991213960270");
    b.version(2);
    b.property("description", 0x4742492ef6d05696L).type(PrimitiveTypeId.STRING).origin("5134746991213960271").done();
    b.alias("Power");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPrimaryUserNeed() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("M1_2_DesignRoadmapping", "PrimaryUserNeed", 0xa3ca47195a3a4b22L, 0x9db2d6b600fc0223L, 0x4742492ef6d0566dL);
    b.class_(false, false, false);
    b.super_("M2_AbstractLanguage.structure.Element", 0x4b68402a1c7b472dL, 0x8c517b3c81719d43L, 0x7157f84cd39fdab8L);
    b.origin("r:bec4dda7-5c83-4544-bebd-5932074c8254(M1_2_DesignRoadmapping.structure)/5134746991213958765");
    b.version(2);
    b.property("description", 0x4742492ef6d0566bL).type(PrimitiveTypeId.STRING).origin("5134746991213958766").done();
    b.alias("Primary User Need");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRequires() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("M1_2_DesignRoadmapping", "Requires", 0xa3ca47195a3a4b22L, 0x9db2d6b600fc0223L, 0x4742492ef6df268cL);
    b.class_(false, false, false);
    b.super_("M2_AbstractLanguage.structure.Link", 0x4b68402a1c7b472dL, 0x8c517b3c81719d43L, 0x7157f84cd376c8cfL);
    b.origin("r:bec4dda7-5c83-4544-bebd-5932074c8254(M1_2_DesignRoadmapping.structure)/5134746991214929548");
    b.version(2);
    b.alias("requires");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSatisfies() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("M1_2_DesignRoadmapping", "Satisfies", 0xa3ca47195a3a4b22L, 0x9db2d6b600fc0223L, 0x4742492ef6dc6ff1L);
    b.class_(false, false, false);
    b.super_("M2_AbstractLanguage.structure.Link", 0x4b68402a1c7b472dL, 0x8c517b3c81719d43L, 0x7157f84cd376c8cfL);
    b.origin("r:bec4dda7-5c83-4544-bebd-5932074c8254(M1_2_DesignRoadmapping.structure)/5134746991214751729");
    b.version(2);
    b.alias("satisfies");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForScreenInterface() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("M1_2_DesignRoadmapping", "ScreenInterface", 0xa3ca47195a3a4b22L, 0x9db2d6b600fc0223L, 0x4742492ef6d05695L);
    b.class_(false, false, false);
    b.super_("M2_AbstractLanguage.structure.Element", 0x4b68402a1c7b472dL, 0x8c517b3c81719d43L, 0x7157f84cd39fdab8L);
    b.origin("r:bec4dda7-5c83-4544-bebd-5932074c8254(M1_2_DesignRoadmapping.structure)/5134746991213958805");
    b.version(2);
    b.property("description", 0x4742492ef6d05696L).type(PrimitiveTypeId.STRING).origin("5134746991213958806").done();
    b.alias("Screen Interface");
    return b.create();
  }
}
